### ISSUE TITLE
DKT Regression

### ISSUE THREAD

**Issue by surtantheta** [BayesWatch/deep-kernel-transfer#11]
Your paper mentions about in-range and out-range mse in the regression use case. However, we don't find these errors separately in the codebase. On running test_regression.py we receive a single MSE. Can you kindly elaborate what this value represents (in-range or out-range) ? 
Is the code and data available only for QMUL or sines also.

**Comment by mpatacchiola** [comment]
Hi @surtantheta I have now added the code for the sines experiments in the folder:

 [https://github.com/BayesWatch/deep-kernel-transfer/tree/master/sines](https://github.com/BayesWatch/deep-kernel-transfer/tree/master/sines)

Follow the instructions in the README for setting up the out-of-range experiments.

**Comment by ZohrehAdabi** [comment]
> 
Hi @mpatacchiola 
I tried to run train_DKT but got the "Matrix not PSD after repeatedly adding jitter" error. Are there any points I need to consider when executing the code?
Thank you in advance.
