### ISSUE TITLE
Downloading Imagenet Data

### ISSUE THREAD

**Issue by g-benton** [BayesWatch/deep-kernel-transfer#13]
It looks like one of the files needed to setup the ImageNet data as used in this repo has moved. When I run the `download_miniImagenet.sh` file I get:

```
--2022-01-11 10:15:16--  http://image-net.org/image/ILSVRC2015/ILSVRC2015_CLS-LOC.tar.gz
Resolving image-net.org (image-net.org)... 171.64.68.16
Connecting to image-net.org (image-net.org)|171.64.68.16|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
```
The website says links to Kaggle as a download source, but I'm not able to find the `ILSVRC2015_CLS-LOC.tar.gz` file available anywhere. Do you have an alternate location to download from by chance?

**Comment by mpatacchiola** [comment]
Hi @g-benton 

Yes we are aware of this problem which has been already discussed in another [issue](https://github.com/BayesWatch/deep-kernel-transfer/issues/8). Unfortunately, the original links have been removed and we are not aware of any other public archive of mini-ImageNet available for download.

As suggested in the other issue, a possible solution is to build the mini-ImageNet from scratch by following [these instructions](https://github.com/yaoyao-liu/mini-imagenet-tools).

If you find another link with the archive let us know and we will be happy to add it in our readme.

**Comment by ZohrehAdabi** [comment]
Hi
You can download miniImageNet from [https://github.com/markdtw/meta-learning-lstm-pytorch](url).
