### ISSUE TITLE
Why there's a need to set_train_data() in DKT_regression.py while testing

### ISSUE THREAD

**Issue by Hstellar** [BayesWatch/deep-kernel-transfer#16]
While running testloop, ideally we won't have target variable or y_support[n] then why do you write self.model.set_train_data(inputs=z_support, targets=y_support[n], strict=False) in line 84. Will it not cause a target leak(or testing the same data which is in train set) while testing?

![image](https://user-images.githubusercontent.com/22677436/191129518-2e382b06-9488-4b84-ba20-06a0b379b3b5.png)

**Comment by mpatacchiola** [comment]
Hi @Hstellar 

The use of the support set at test time is standard practice in the few-shot setting. 

In few-shot learning, the model can access the support data (context) and use them to make the prediction on the query data. The performance of the model on the query set is used to evaluate the final accuracy. 

Hope this helps.

**Comment by mpatacchiola** [comment]
The use of the method `set_train_data()` is a call to the underlying GPytorch method, [see the documentation here](https://docs.gpytorch.ai/en/latest/models.html#gpytorch.models.ExactGP.set_train_data).

In practice this is not training the model, but just setting the base data used by the GP for inference.

**Comment by Hstellar** [comment]
Thank you for quick reply. So if I understand correctly, in testloop we write x_query instead of x_all[n] when we want to evaluate test performance in line 91.

![image](https://user-images.githubusercontent.com/22677436/191300544-248498da-42ec-4af8-aa38-f9f79223e07d.png)

**Comment by mpatacchiola** [comment]
Yes, if you are only interested in the prediction of the models for the query points then you will need to use x_query.

Then you will have to compare the prediction of the model against the true labels (y_query). The score on the query set is what matters in terms of evaluation.

**Comment by Hstellar** [comment]
Thank you so much! This solves my doubt.
