### ISSUE TITLE
dataset load issue: I have replicated the code, however, after downloading the datasets (cub,emnist etc.), i am unable to train the model.

### ISSUE THREAD

**Issue by Shantan243** [BayesWatch/deep-kernel-transfer#17]
I dont see .json files in the dataset, however, script requires the json files to train the model. iam i missing something.

base_file = configs.data_dir[params.dataset] + 'base.json'
KeyError: 'C:\\Users\\shant_w5mrdz3\\OneDrive\\Desktop\\deep-kernel-transfer-master\\filelists\\emnist\\emnist+base.json'

**Comment by mpatacchiola** [comment]
Hi @Shantan243 you should download and preprocess the datasets by using the scripts in the repository:

```
cd filelists/DATASET_NAME/
sh download_DATASET_NAME.sh
```

Replace `DATASET_NAME` with one of the following: omniglot, CUB, miniImagenet, emnist, QMUL. Those scripts will download and create the json files you are missing.

See [this section](https://github.com/BayesWatch/deep-kernel-transfer#experiments) of the Readme for more details.

**Comment by mpatacchiola** [comment]
Closed for inactivity.
