### ISSUE TITLE
whats the role of DKT? How Bayesian is being used in this paper (need under the hood explanation) and how bayesian and DKT are complimenting each other..

### ISSUE THREAD

**Issue by Shantan243** [BayesWatch/deep-kernel-transfer#18]
Hi,
The paper has not explained details of how DKT is creating the difference except in metrics which shows experiement results - Need how DKT is identified as the influencer/factor, what is the role/objective of DKT. Also in papaer, we see Baseline and Baseline++ models , what are these? Could you please give more details/explanations of these Baseline/Baseline++

**Comment by mpatacchiola** [comment]
Hi @Shantan243 

`The paper has not explained details of how DKT is creating the difference except in metrics which shows experiement results - Need how DKT is identified as the influencer/factor, what is the role/objective of DKT. `

I am not sure what you mean here, can you reformulate the question?

`Also in papaer, we see Baseline and Baseline++ models , what are these? Could you please give more details/explanations of these Baseline/Baseline++`

Those baselines have been proposed by Chen et al. (2019). They are briefly discussed in the paper (Section 4, Related Work). They use a pretrained backbone that is fine-tuned on a task. Give a look at Chen et al. (2019) for more details.

**Comment by mpatacchiola** [comment]
Closed for inactivity.
