### ISSUE TITLE
Hello! Just curious to know if this model works for Binary class classification prob. I had tried it but seems no luck!

### ISSUE THREAD

**Issue by Shantan243** [BayesWatch/deep-kernel-transfer#19]

**Comment by mpatacchiola** [comment]
Hi @Shantan243, yes the method can be used to deal with binary classification problems. If your dataset is different from those used in our work then you may need to tune the hyper-parameters and training schedule to get best results.

**Comment by Shantan243** [comment]
Thanks @mpatacchiola. It has worked for me..
