### ISSUE TITLE
Could someone share the typical architecture with DKT of this model.

### ISSUE THREAD

**Issue by Shantan243** [BayesWatch/deep-kernel-transfer#20]

**Comment by mpatacchiola** [comment]
Hi @Shantan243 .

You can find the implementation for DKT (regression) in the repository at [this address](https://github.com/BayesWatch/deep-kernel-transfer/blob/master/methods/DKT_regression.py). The code for the DKT classification is available [here](https://github.com/BayesWatch/deep-kernel-transfer/blob/master/methods/DKT.py) instead. Give a look at the `DKT` class in both file, it is pretty simple to define a DKT model. Note that, there is also an associated train and test look under the same class.

For DKT regression, the only object you need to provide is the backbone (as you can see at [this line](https://github.com/BayesWatch/deep-kernel-transfer/blob/master/methods/DKT_regression.py#L19)). The backbone can be your own (e.g. ResNet) or one of the backbones that you can find [here](https://github.com/BayesWatch/deep-kernel-transfer/blob/master/backbone.py) in our repo. We have used a Conv4 in our experiments.

Moreover, if you are using DKT for regression I suggest to give a look at the code for the sine-waves experiments that you can find [here](https://github.com/BayesWatch/deep-kernel-transfer/blob/master/sines/train_DKT.py). This code is self-contained, and you can see how to create a DKT model from scratch by using the ExactGP model from GPytorch.
