### ISSUE TITLE
Why the parameters are updated on the support set data?

### ISSUE THREAD

**Issue by serre20** [BayesWatch/deep-kernel-transfer#22]
I think it will be better to update the parameters on the query set, rather than on the support set. 
For the reason that the evaluation process on the query set is the simulation for the meta-test setting.

**Comment by mpatacchiola** [comment]
Hi @2020213484, from an empirical point of view using both support and query sets for the update leads to significantly better performance. We have observed this in our experiments  and it has been confirmed in a [separate work](https://arxiv.org/abs/2007.10417).
