### ISSUE TITLE
the issue about miniImagenet dataset

### ISSUE THREAD

**Issue by indussky8** [BayesWatch/deep-kernel-transfer#5]
"wget http://image-net.org/image/ILSVRC2015/ILSVRC2015_CLS-LOC.tar.gz" is not available.
The requested URL /image/ILSVRC2015/ILSVRC2015_CLS-LOC.tar.gz was not found on this server.
So, could you please share the miniImagenet dataset used in your experiments? (such as google drive)
Thanks!

**Comment by mpatacchiola** [comment]
Hi @indussky8 

There are copyright issues and we cannot reshare the dataset.
I suggest you follow the instruction on the official website or build the dataset as suggested [here](https://github.com/yaoyao-liu/mini-imagenet-tools).
