### ISSUE TITLE
MAML regression 

### ISSUE THREAD

**Issue by ZohrehAdabi** [BayesWatch/deep-kernel-transfer#6]
Hi @mpatacchiola, @elliotjcrowley 

Could you provide the code for MAML regression on QMUL (head pose detection) please?
Thanks in advancce.

**Comment by mpatacchiola** [comment]
It is the same code used for [the classification](https://github.com/BayesWatch/deep-kernel-transfer/blob/master/methods/maml.py) case. For the regressor, you just need to replace the output softmax with a single linear unit.
