### ISSUE TITLE
miniImageNet link download not working

### ISSUE THREAD

**Issue by surtantheta** [BayesWatch/deep-kernel-transfer#8]
I want to prepare the dataset for miniImageNet but the URL for it doesn't exist. Kindly provide a valid link.

**Comment by mpatacchiola** [comment]
Hi @surtantheta,

The official link to miniImagenet does not work anymore, as we reported in [this issue](https://github.com/BayesWatch/deep-kernel-transfer/issues/5). Unfortunately, we do not have a copy to share. A possible solution is to build the dataset from scratch by following [these instructions](https://github.com/yaoyao-liu/mini-imagenet-tools).
